CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Cities" (
    "CityId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("CityId")
);

CREATE TABLE "Citizenships" (
    "CitizenshipId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CitizenshipName" text NOT NULL,
    CONSTRAINT "PK_Citizenships" PRIMARY KEY ("CitizenshipId")
);

CREATE TABLE "Disabilities" (
    "DisabilityId" integer GENERATED BY DEFAULT AS IDENTITY,
    "DisabilityStatus" text NOT NULL,
    CONSTRAINT "PK_Disabilities" PRIMARY KEY ("DisabilityId")
);

CREATE TABLE "FamilyStatuses" (
    "FamilyStatusId" integer GENERATED BY DEFAULT AS IDENTITY,
    "StatusName" text NOT NULL,
    CONSTRAINT "PK_FamilyStatuses" PRIMARY KEY ("FamilyStatusId")
);

CREATE TABLE "Clients" (
    "ClientId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Surname" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "PassportSeries" text NOT NULL,
    "PassportNumber" text NOT NULL,
    "IssuedBy" text NOT NULL,
    "DateOfIssue" timestamp with time zone NOT NULL,
    "IdentificationNumber" text NOT NULL,
    "PlaceOfBirth" text NOT NULL,
    "LocationAddress" text NOT NULL,
    "CityId" integer NOT NULL,
    "HomePhone" text NULL,
    "MobilePhone" text NULL,
    "Email" text NULL,
    "Company" text NULL,
    "JobTitle" text NULL,
    "RegistrationAddress" text NOT NULL,
    "CitizenshipId" integer NOT NULL,
    "DisabilityId" integer NOT NULL,
    "FamilyStatusId" integer NOT NULL,
    "IsPensioner" boolean NOT NULL,
    "MonthIncome" numeric NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("ClientId"),
    CONSTRAINT "FK_Clients_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("CityId") ON DELETE CASCADE,
    CONSTRAINT "FK_Clients_Citizenships_CitizenshipId" FOREIGN KEY ("CitizenshipId") REFERENCES "Citizenships" ("CitizenshipId") ON DELETE CASCADE,
    CONSTRAINT "FK_Clients_Disabilities_DisabilityId" FOREIGN KEY ("DisabilityId") REFERENCES "Disabilities" ("DisabilityId") ON DELETE CASCADE,
    CONSTRAINT "FK_Clients_FamilyStatuses_FamilyStatusId" FOREIGN KEY ("FamilyStatusId") REFERENCES "FamilyStatuses" ("FamilyStatusId") ON DELETE CASCADE
);

CREATE INDEX "IX_Clients_CitizenshipId" ON "Clients" ("CitizenshipId");

CREATE INDEX "IX_Clients_CityId" ON "Clients" ("CityId");

CREATE INDEX "IX_Clients_DisabilityId" ON "Clients" ("DisabilityId");

CREATE INDEX "IX_Clients_FamilyStatusId" ON "Clients" ("FamilyStatusId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240131202348_InitialMigration', '7.0.15');

COMMIT;

